server:
  port: 8080

spring:
  profiles:
    active: dev

  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: NTg0ZTVmYzQ4Y2EwNDc2YmIzY2FhYjFiM2YwYTEwMTdmZTY1ZjYzYjQxZGYxMWU5ZTYxYmY2Y2M2YzU5YjA=

  cloud:
    gateway:
      routes:
        # User Service
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        # Account Service
        - id: account-service-route
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

        # Transaction Service
        - id: transaction-service-route
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**

        # Credit Service
        - id: credit-service-route
          uri: lb://CREDIT-SERVICE
          predicates:
            - Path=/credits/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

application:
  security:
    jwt:
      expiration: 36000000