spring.application.name=userService
server.port=8081

eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${instanceId:${random.value}}

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true